// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATK7x8WlQyi6ZSata5zTRtdeNQJqWzQDY',
    appId: '1:927677242341:web:692049359debd9aff06d0c',
    messagingSenderId: '927677242341',
    projectId: 'ludo-game-25f59',
    authDomain: 'ludo-game-25f59.firebaseapp.com',
    storageBucket: 'ludo-game-25f59.firebasestorage.app',
    measurementId: 'G-89T01J4T79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnEw7fAXsWo14JcNEk7z8v3LYTLA12BDE',
    appId: '1:927677242341:android:11d7933c8d15a044f06d0c',
    messagingSenderId: '927677242341',
    projectId: 'ludo-game-25f59',
    storageBucket: 'ludo-game-25f59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOQcFhct7JgopXqN4hbPGtiAexvRD-Qnw',
    appId: '1:927677242341:ios:b73ccda4d4079d5ff06d0c',
    messagingSenderId: '927677242341',
    projectId: 'ludo-game-25f59',
    storageBucket: 'ludo-game-25f59.firebasestorage.app',
    iosBundleId: 'com.ludopremium.ludoFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOQcFhct7JgopXqN4hbPGtiAexvRD-Qnw',
    appId: '1:927677242341:ios:b73ccda4d4079d5ff06d0c',
    messagingSenderId: '927677242341',
    projectId: 'ludo-game-25f59',
    storageBucket: 'ludo-game-25f59.firebasestorage.app',
    iosBundleId: 'com.ludopremium.ludoFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATK7x8WlQyi6ZSata5zTRtdeNQJqWzQDY',
    appId: '1:927677242341:web:d1104d9db7abd978f06d0c',
    messagingSenderId: '927677242341',
    projectId: 'ludo-game-25f59',
    authDomain: 'ludo-game-25f59.firebaseapp.com',
    storageBucket: 'ludo-game-25f59.firebasestorage.app',
    measurementId: 'G-FZ2X1JNGHP',
  );
}
